import { company } from "@/data/content";

export function downloadTextFile(
  filename: string,
  content: string,
  mime = "text/plain;charset=utf-8"
) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function buildDocumentContent(
  title: string,
  category: string,
  summary: string
) {
  return `${company.name}
${"=".repeat(company.name.length)}

${title}
Category: ${category}
Published: ${new Date().toLocaleDateString("en-UG", { dateStyle: "long" })}

${summary}

---
This is a placeholder document generated by the ${company.name} website.
Replace with your official PDF or report file when ready.

Contact: ${company.email} | ${company.phone}
${company.address}
`;
}

export function downloadDocument(
  title: string,
  category: string,
  summary: string,
  extension = "txt"
) {
  const safeName = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  const content = buildDocumentContent(title, category, summary);
  downloadTextFile(`${safeName}.${extension}`, content);
}